from flask_app.blueprints.index_bp import index_bp
from flask_app.blueprints.victims_average_bp import victims_average_bp
from flask_app.blueprints.most_active_groups_bp import active_groups_bp
from flask_app.blueprints.unique_groups_bp import unique_groups_bp
from flask_app.blueprints.correlation_victims_for_events_bp import corr_victims_for_events_bp
