from blueprints.index_bp import index_bp
from blueprints.victims_average_bp import victims_average_bp
from blueprints.most_active_groups_bp import active_groups_bp
from blueprints.unique_groups_bp import unique_groups_bp
from blueprints.correlation_victims_for_events_bp import corr_victims_for_events_bp
